env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  arrow-spacing:
    - error
  eqeqeq:
    - error
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  no-console:
    - 0
  no-trailing-spaces:
    - error
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - single
  semi:
    - error
    - never